stages:
  - compile
  - build

services:
  - docker:dind

mvn:package:
  stage: compile
  image: maven:3.3.9-jdk-8
  script:
    - mvn -s .maven/settings.xml package
  artifacts:
    expire_in: 1 day
    paths:
      - target/lib/trugger-6.2.0.jar
      - target/lib/jsoup-1.10.2.jar
      - target/lib/mongo-java-driver-3.0.4.jar
      - channels/boteco-channel-email/target/boteco-channel-email-*.jar
      - channels/boteco-channel-irc/target/boteco-channel-irc-*.jar
      - channels/boteco-channel-pushover/target/boteco-channel-pushover-*.jar
      - channels/boteco-channel-telegram/target/boteco-channel-telegram-*.jar
      - channels/boteco-channel-user/target/boteco-channel-user-*.jar
      - main/boteco/target/boteco-*.jar
      - main/boteco-amq-client/target/boteco-amq-client-*.jar
      - main/boteco-event-bus/target/boteco-event-bus-*.jar
      - main/boteco-event-processor/target/boteco-event-processor-*.jar
      - main/boteco-message-formatter/target/boteco-message-formatter-*.jar
      - main/boteco-message-processor/target/boteco-message-processor-*.jar
      - main/boteco-rest-api/target/boteco-rest-api-*.jar
      - main/boteco-rest-client/target/boteco-rest-client-*.jar
      - persistence/boteco-persistence-irc/target/boteco-persistence-irc-*.jar
      - persistence/boteco-persistence-karma/target/boteco-persistence-karma-*.jar
      - persistence/boteco-persistence-manager/target/boteco-persistence-manager-*.jar
      - persistence/boteco-persistence-mongodb/target/boteco-persistence-mongodb-*.jar
      - persistence/boteco-persistence-request/target/boteco-persistence-request-*.jar
      - persistence/boteco-persistence-subscription/target/boteco-persistence-subscription-*.jar
      - persistence/boteco-persistence-user/target/boteco-persistence-user-*.jar
      - plugins/boteco-plugin-definitions/target/boteco-plugin-definitions-*.jar
      - plugins/boteco-plugin-diceroll/target/boteco-plugin-diceroll-*.jar
      - plugins/boteco-plugin-facts/target/boteco-plugin-facts-*.jar
      - plugins/boteco-plugin-help/target/boteco-plugin-help-*.jar
      - plugins/boteco-plugin-irc/target/boteco-plugin-irc-*.jar
      - plugins/boteco-plugin-karma/target/boteco-plugin-karma-*.jar
      - plugins/boteco-plugin-manager/target/boteco-plugin-manager-*.jar
      - plugins/boteco-plugin-ping/target/boteco-plugin-ping-*.jar
      - plugins/boteco-plugin-providers/target/boteco-plugin-providers-*.jar
      - plugins/boteco-plugin-redhat/target/boteco-plugin-redhat-*.jar
      - plugins/boteco-plugin-request/target/boteco-plugin-request-*.jar
      - plugins/boteco-plugin-subscription/target/boteco-plugin-subscription-*.jar
      - plugins/boteco-plugin-user/target/boteco-plugin-user-*.jar
      - plugins/boteco-plugin-weather/target/boteco-plugin-weather-*.jar
      - plugins/boteco-plugin-xgh/target/boteco-plugin-xgh-*.jar
      - plugins/boteco-plugin-timebomb/target/boteco-plugin-timebomb-*.jar
      - providers/boteco-provider-chucknorris/target/boteco-provider-chucknorris-*.jar
      - providers/boteco-provider-urbandictionary/target/boteco-provider-urbandictionary-*.jar
      - providers/boteco-provider-yahooweather/target/boteco-provider-yahooweather-*.jar

docker:build:
  image: docker:latest
  stage: build
  script:
    - docker build -t devnull-tools/boteco .
    - docker login -p $DOCKER_TOKEN docker-registry.default.svc:5000
    - docker tag devnull-tools/boteco devnull-tools/boteco docker-registry.default.svc:5000/$OPENSHIFT_NAMESPACE/boteco
    - docker push devnull-tools/boteco docker-registry.default.svc:5000/$OPENSHIFT_NAMESPACE/boteco
