= Karma Plugin

This is a simple karma plugin. It will parse any (++/--) terms that arrives in channels and computes the
karma.

This plugin uses a MongoDB Database to store the karmas outside the JVM so make sure you have a MongoDB instance
running and make sure you have configured the `boteco-plugin-mongodb`.

== Querying ranks

There is a command `rank` that allows queries to the karma database. The options are:

- Query for a specific term by using the term as is
- Query for a _like_ term by using `*` as wildcard
- Reverse order by using the prefix `!` (can be combined with the other options)

== Configuration

You can configure the karma expressions by creating a config named `tools.devnull.boteco.plugins.karma` with the
following key patterns:

${key}.karma:: the value of this property will be used instead of the word karma
${key}.term:: the value of this property will be used instead of the "karma" term
${key}.unit:: the value of this property will be used instead of the "points" term
${key}:: the value of this property will be used instead of the default template

The default template is `%t has now %n %u of %k`. The placeholders are:


